

## Let's explore the Pathlib library

from pathlib import Path

def read_minerU_output():
        """
        It takes the address of the folder where minerU has stored its output and will access the markdown and json files
        from it. It is upto us to use whichever we want to out of these two output files.

        **Args:**
        minerU_output_path (path): It is the path of the folder where minerU has stored its parsed output files.

        **Returns:**
        Parsed_JSON_file : It is the parsed data in json format.
        Parsed_markdown_file : It is the parsed data in markdown format.

        """
    ## Let's explore the Pathlib library

        # set directory
        new_cwd_path = Path("C:\\Users\\Hp\\MinerU")
        content_of_cwd = list(new_cwd_path.iterdir())
        
        folders_cwd = []
        for items in new_cwd_path.iterdir():
            if items.is_dir():
                  folders_cwd.append(items)
        output_dir = str(folders_cwd[1])   
        json_output_path = (Path(output_dir)).joinpath("layout.json")
        md_output_path = (Path(output_dir)).joinpath("full.md")
        
        content_of_json =  json_output_path.read_text(encoding="utf-8")
        content_of_md = md_output_path.read_text(encoding="utf-8")
              
                        

        # lets find out the folders generated by minerU in its default directory
        # 1- Get all folders in the diretcory  (done)
        # 2- Filter out only sub-directory (done)
        # 3- Fetch the top most sub-directory (done)
        # 4- create the path for fetching the json file from the sub-directory
        # 5- Read the layout.json file from the sub-directory address
         
        return content_of_md, content_of_json


"""
        # create folder in the same directory
        parsed_output_path = new_cwd_path.joinpath("parsed_output","layout.json")
        # read the json file in the RAG folder
        dummy_parsed_json_path = new_cwd_path.joinpath(f"{list_of_json_files}")
        content_json_file = dummy_parsed_json_path.read_text(encoding="utf-8")

        # move file to folder parsed_output
        with parsed_output_path.open(mode='wb') as file:
            file.write(dummy_parsed_json_path.read_bytes())

        return list_of_json_files
"""

content_of_parsed_file = read_minerU_output()
print(content_of_parsed_file)